-- TEMPORARY: Disable RLS for Development
-- WARNING: Only use this during development! Re-enable RLS before production.

-- Disable RLS on all tables
ALTER TABLE enterprises DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sub_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE remote_reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE facility_qc DISABLE ROW LEVEL SECURITY;
ALTER TABLE on_site_qc DISABLE ROW LEVEL SECURITY;
ALTER TABLE pickup_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE pickup_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE logistics_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE logistics_admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE credit_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE disputes DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE epr_certificates DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_orders DISABLE ROW LEVEL SECURITY;

SELECT 'RLS DISABLED FOR DEVELOPMENT' as status;

-- Note: When you're ready for production, run this to re-enable RLS:
-- ALTER TABLE [table_name] ENABLE ROW LEVEL SECURITY;
-- Then add proper RLS policies based on your authentication setup
