/**
 * STATUS: COMPLETE
 * Role-permission mappings mirroring backend/app/core/permissions.py ROLE_PERMISSIONS.
 * Single source of truth for which roles have which permissions.
 */

import type { UserRole } from '@/types';
import { Permission, type PermissionValue } from './constants';

export const ROLE_PERMISSIONS: Record<UserRole, Set<PermissionValue>> = {
  super_admin: new Set([Permission.ALL]),

  ops_admin: new Set([
    Permission.REVIEW_SUBMISSIONS,
    Permission.APPROVE_PICKUPS,
    Permission.VIEW_ALL_ASSETS,
    Permission.MANAGE_REMOTE_REVIEW_QUEUE,
    Permission.MANAGE_ENTERPRISE_APPLICATIONS,
    Permission.USER_READ,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.LOGISTICS_MANAGE,
    Permission.EMPLOYEE_READ,
    Permission.EMPLOYEE_CREATE,
    Permission.EMPLOYEE_UPDATE,
    Permission.EMPLOYEE_DELETE,
    Permission.PRICING_READ,
    Permission.ANALYTICS_READ,
    Permission.ASSET_READ,
    Permission.ASSET_CREATE,
    Permission.ASSET_UPDATE,
    Permission.ASSET_DELETE,
    Permission.BATCH_READ,
    Permission.BATCH_CREATE,
    Permission.BATCH_UPDATE,
    Permission.BATCH_DELETE,
    Permission.BATCH_APPROVE,
    Permission.BRANCH_READ,
    Permission.BRANCH_CREATE,
    Permission.BRANCH_UPDATE,
    Permission.BRANCH_DELETE,
    Permission.ENTERPRISE_READ,
    Permission.ENTERPRISE_CREATE,
    Permission.ENTERPRISE_UPDATE,
    Permission.ENTERPRISE_DELETE,
    Permission.SUBMISSION_VIEW,
    Permission.SUBMISSION_CREATE,
    Permission.SUBMISSION_UPDATE,
    Permission.REVIEW_VIEW,
    Permission.REVIEW_CREATE,
    Permission.REVIEW_UPDATE,
    Permission.PICKUP_VIEW,
    Permission.PICKUP_CREATE,
    Permission.PICKUP_UPDATE,
    Permission.PICKUP_ASSIGN,
    Permission.PAYOUT_VIEW,
    Permission.PAYOUT_CREATE,
    Permission.PAYOUT_PROCESS,
    Permission.NOTIFICATION_CREATE,
    Permission.DISPUTE_VIEW,
    Permission.DISPUTE_MANAGE,
    Permission.REMOTE_REVIEW,
    Permission.FACILITY_QC,
    Permission.HANDLE_DISPUTES,
    Permission.VIEW_REPORTS,
    Permission.VIEW_EPR_CERTIFICATES,
    Permission.MANAGE_EPR_CERTIFICATES,
    Permission.HANDLE_ESCALATIONS,
    Permission.OVERRIDE_DECISIONS,
    Permission.VIEW_ALL_ENTERPRISES,
    Permission.MANAGE_ENTERPRISES,
  ]),

  org_admin: new Set([
    Permission.APPROVE_PICKUPS,
    Permission.MANAGE_BRANCHES,
    Permission.MANAGE_IT_ADMINS,
    Permission.VIEW_FINANCIAL_REPORTS,
    Permission.APPROVE_HIGH_VALUE,
    Permission.VIEW_ENTERPRISE_ANALYTICS,
    Permission.VIEW_EPR_CERTIFICATES,
    Permission.VIEW_WALLET,
    Permission.USER_READ,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.EMPLOYEE_READ,
    Permission.EMPLOYEE_CREATE,
    Permission.EMPLOYEE_UPDATE,
    Permission.EMPLOYEE_DELETE,
    Permission.ASSET_READ,
    Permission.ASSET_CREATE,
    Permission.ASSET_UPDATE,
    Permission.ASSET_DELETE,
    Permission.BATCH_READ,
    Permission.BATCH_CREATE,
    Permission.BATCH_UPDATE,
    Permission.BATCH_DELETE,
    Permission.BATCH_APPROVE,
    Permission.BRANCH_READ,
    Permission.BRANCH_CREATE,
    Permission.BRANCH_UPDATE,
    Permission.BRANCH_DELETE,
    Permission.ENTERPRISE_READ,
    Permission.ENTERPRISE_UPDATE,
    Permission.SUBMISSION_VIEW,
    Permission.SUBMISSION_CREATE,
    Permission.SUBMISSION_UPDATE,
    Permission.REVIEW_VIEW,
    Permission.REVIEW_CREATE,
    Permission.REVIEW_UPDATE,
    Permission.PICKUP_VIEW,
    Permission.PICKUP_CREATE,
    Permission.PICKUP_UPDATE,
    Permission.PAYOUT_VIEW,
    Permission.PAYOUT_CREATE,
    Permission.DISPUTE_VIEW,
    Permission.DISPUTE_MANAGE,
  ]),

  it_admin: new Set([
    Permission.MANAGE_ASSETS,
    Permission.MANAGE_BATCHES,
    Permission.VIEW_PAYOUTS,
    Permission.SUBMIT_DISPUTES,
    Permission.MANAGE_ENTERPRISE_SETTINGS,
    Permission.MANAGE_PICKUP_LOCATIONS,
    Permission.SUBMIT_PICKUP_FOR_APPROVAL,
    Permission.EMPLOYEE_READ,
    Permission.EMPLOYEE_CREATE,
    Permission.EMPLOYEE_UPDATE,
    Permission.EMPLOYEE_DELETE,
    Permission.ASSET_READ,
    Permission.ASSET_CREATE,
    Permission.ASSET_UPDATE,
    Permission.ASSET_DELETE,
    Permission.BATCH_READ,
    Permission.BATCH_CREATE,
    Permission.BATCH_UPDATE,
    Permission.BATCH_DELETE,
    Permission.BRANCH_READ,
    Permission.BRANCH_CREATE,
    Permission.ENTERPRISE_READ,
    Permission.SUBMISSION_VIEW,
    Permission.SUBMISSION_CREATE,
    Permission.SUBMISSION_UPDATE,
    Permission.PICKUP_VIEW,
    Permission.PICKUP_CREATE,
    Permission.PAYOUT_VIEW,
    Permission.DISPUTE_VIEW,
    Permission.DISPUTE_CREATE,
  ]),

  employee: new Set([
    Permission.VIEW_ASSIGNED_ASSETS,
    Permission.SUBMIT_DEVICE_EVALUATION,
    Permission.ASSET_READ,
    Permission.ASSET_UPDATE,
    Permission.ENTERPRISE_READ,
    Permission.DISPUTE_VIEW,
    Permission.DISPUTE_CREATE,
    Permission.SUBMISSION_VIEW,
    Permission.SUBMISSION_CREATE,
    Permission.SUBMISSION_UPDATE,
  ]),

  logistics_admin: new Set([
    Permission.VIEW_PICKUP_REQUESTS,
    Permission.ASSIGN_PICKUPS,
    Permission.MANAGE_LOGISTICS_USERS,
    Permission.VIEW_PICKUP_ANALYTICS,
    Permission.LOGISTICS_MANAGE,
    Permission.PICKUP_VIEW,
    Permission.PICKUP_ASSIGN,
  ]),

  logistics_user: new Set([
    Permission.VIEW_ASSIGNED_PICKUPS,
    Permission.PERFORM_ONSITE_QC,
    Permission.COLLECT_DEVICES,
    Permission.UPLOAD_PICKUP_PROOF,
    Permission.PICKUP_VIEW,
    Permission.PICKUP_UPDATE,
    Permission.REVIEW_CREATE,
  ]),
};
